name: cripstv_academy
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  get_it: ^7.6.4
  url_strategy: ^0.2.0
  flutter_svg: ^2.0.2
  gradient_borders: ^0.2.0
 
  cached_network_image: ^3.3.1
  flutter_hooks: ^0.20.3
  pinput: ^3.0.1
  intl: ^0.19.0
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  event_bus: ^2.0.0
  provider: ^6.1.1

  uuid: ^4.0.0
  
  url_launcher: ^6.1.3
  shimmer_animation: ^2.1.0+1
  dropdown_search: ^5.0.6
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
